### ISSUE TITLE
[Bug]: the date conversion has still issue even after the update of number of days 

### ISSUE THREAD

**Issue by novaprime-code** [anuzpandey/laravel-nepali-date#13] opened 2024-05-10 18:04 UTC
### What happened?

I cannot convert 2081-02-32 to AD date

### How to reproduce the bug

Try converting 2081-02-32 to AD

### Package Version

1.6

### PHP Version

8.2

### Laravel Version

10.0

### Which operating systems does with happen with?

Linux

### Notes

Thank you in advance

**Comment by anuzpandey** [comment] 2024-05-11 20:11
Hello @novaprime-code.

The issue has been identified and to solve this problem I might have to re-write the whole `toEnglishDate()` function. Since the package use `Carbon` extension, the problem is, it cannot set `32` to any of months. I will get this fixed by the end of the week.

The feature you requested for `daysInMonth` and `daysInYear` has been completed. It will be available from the release of [1.7.0](https://github.com/anuzpandey/laravel-nepali-date/releases/tag/1.7.0).

**Comment by novaprime-code** [comment] 2024-05-11 20:39
Thank you so much

**Closed as completed** 2024-05-12 10:39 UTC
Labels: bug
